default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None #If None, will be computed
  verbose: True
  arch: 'fno'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

    # FNO related
  fno:
    data_channels: 3
    out_channels: 3
    n_modes: [8,8,10]
    hidden_channels: 32
    projection_channel_ratio: 2
    n_layers: 4
    norm: None
    use_channel_mlp: 1
    channel_mlp_expansion: 0.5
    channel_mlp_dropout: 0

    # Optimizer
  opt:
    n_epochs: 10 # 500
    learning_rate: 3e-4
    training_loss: 'h1'
    weight_decay: 1e-4
    amp_autocast: False
    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 50 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 100
    gamma: 0.5

  # Dataset related
  data:
    folder: ../data/damage_sensor/
    batch_size: 10
    n_train: 450
    train_resolution: 32
    test_resolutions: [32] #, 1024] #, 1024] 
    test_batch_sizes: [10] #, 4] #, 1]
    encode_input: True
    encode_output: False

    # Patching
  patching:
    levels: 0 #1
    padding: 0 #0.078125
    stitching: False #True

    # Weights and biases
  wandb:
    log: True
    name: None # If None, config will be used but you can override it here
    group: '' 
    project: "damage_sensor"
    entity: "liuyangyuanchen-jhu" # put your username here
    sweep: False
    log_output: True
    eval_interval: 1

  # ckpt and model
  ckpt:
    save_dir: './ckpt/fno3d_test/'
    save_every: 10