#!/bin/bash -l
#SBATCH --job-name=FNO
#SBATCH --partition=a100
#SBATCH --time=30:00:00
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --output=training-%J.log
#SBATCH --account=sghosh20_gpu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=yliu664@jh.edu

ml load gcc/9.3.0
ml load python/3.9.15

source /scratch4/sghosh20/yang/no_playground/neuralop/bin/activate
torchrun --nproc_per_node=1 train_sensor_mask.py
